<?xml version="1.0" encoding="utf-8"?><Database Name="DB_ENROLLMENTSYSTEM" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-L6FJ621L\SQLEXPRESS;Initial Catalog=DB_ENROLLMENTSYSTEM;Integrated Security=True" SettingsObjectName="DBMSEnrollment.Properties.Settings" SettingsPropertyName="DB_ENROLLMENTSYSTEMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBLADMIN" Member="TBLADMINs">
    <Type Name="TBLADMIN">
      <Column Name="ADMIN_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ADMIN_NO" Type="System.String" DbType="VarChar(11)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ADMIN_FNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_MNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_LNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_ROLE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADMIN_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TBLCOURSE" Member="TBLCOURSEs">
    <Type Name="TBLCOURSE">
      <Column Name="COURSE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="COURSE_CODE" Type="System.String" DbType="VarChar(12)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="COURSE_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="COURSE_UNITS" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="COURSE_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLCOURSE_TBLGRADE" Member="TBLGRADEs" ThisKey="COURSE_ID" OtherKey="COURSE_ID" Type="TBLGRADE" />
      <Association Name="TBLCOURSE_TBLPROGRAM" Member="TBLPROGRAMs" ThisKey="COURSE_ID" OtherKey="COURSE_ID" Type="TBLPROGRAM" />
      <Association Name="TBLPROGRAM_TBLCOURSE" Member="TBLPROGRAM" ThisKey="PROG_ID" OtherKey="PROG_ID" Type="TBLPROGRAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLENROLLMENT" Member="TBLENROLLMENTs">
    <Type Name="TBLENROLLMENT">
      <Column Name="ENROLL_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ENROLL_NO" Type="System.String" DbType="VarChar(12)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ENROLL_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ENROLL_TIME" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="ENROLL_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLSTUDENT_TBLENROLLMENT" Member="TBLSTUDENT" ThisKey="STUD_ID" OtherKey="STUD_ID" Type="TBLSTUDENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLGRADE" Member="TBLGRADEs">
    <Type Name="TBLGRADE">
      <Column Name="GRADE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GRADE_VAL" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COURSE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLCOURSE_TBLGRADE" Member="TBLCOURSE" ThisKey="COURSE_ID" OtherKey="COURSE_ID" Type="TBLCOURSE" IsForeignKey="true" />
      <Association Name="TBLINSTRUCTOR_TBLGRADE" Member="TBLINSTRUCTOR" ThisKey="INS_ID" OtherKey="INS_ID" Type="TBLINSTRUCTOR" IsForeignKey="true" />
      <Association Name="TBLPROGRAM_TBLGRADE" Member="TBLPROGRAM" ThisKey="PROG_ID" OtherKey="PROG_ID" Type="TBLPROGRAM" IsForeignKey="true" />
      <Association Name="TBLSTUDENT_TBLGRADE" Member="TBLSTUDENT" ThisKey="STUD_ID" OtherKey="STUD_ID" Type="TBLSTUDENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLINSTRUCTOR" Member="TBLINSTRUCTORs">
    <Type Name="TBLINSTRUCTOR">
      <Column Name="INS_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INS_NO" Type="System.String" DbType="VarChar(9)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="INS_FNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_MNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_LNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_GENDER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_BDAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="INS_MOBILE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="INS_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLINSTRUCTOR_TBLGRADE" Member="TBLGRADEs" ThisKey="INS_ID" OtherKey="INS_ID" Type="TBLGRADE" />
      <Association Name="TBLINSTRUCTOR_TBLPROGRAM" Member="TBLPROGRAMs" ThisKey="INS_ID" OtherKey="INS_ID" Type="TBLPROGRAM" />
      <Association Name="TBLPROGRAM_TBLINSTRUCTOR" Member="TBLPROGRAM" ThisKey="PROG_ID" OtherKey="PROG_ID" Type="TBLPROGRAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLPROGRAM" Member="TBLPROGRAMs">
    <Type Name="TBLPROGRAM">
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PROG_NO" Type="System.String" DbType="VarChar(10)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PROG_DESC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PROG_CREDITS" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="PROG_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COURSE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLPROGRAM_TBLCOURSE" Member="TBLCOURSEs" ThisKey="PROG_ID" OtherKey="PROG_ID" Type="TBLCOURSE" />
      <Association Name="TBLPROGRAM_TBLGRADE" Member="TBLGRADEs" ThisKey="PROG_ID" OtherKey="PROG_ID" Type="TBLGRADE" />
      <Association Name="TBLPROGRAM_TBLINSTRUCTOR" Member="TBLINSTRUCTORs" ThisKey="PROG_ID" OtherKey="PROG_ID" Type="TBLINSTRUCTOR" />
      <Association Name="TBLCOURSE_TBLPROGRAM" Member="TBLCOURSE" ThisKey="COURSE_ID" OtherKey="COURSE_ID" Type="TBLCOURSE" IsForeignKey="true" />
      <Association Name="TBLINSTRUCTOR_TBLPROGRAM" Member="TBLINSTRUCTOR" ThisKey="INS_ID" OtherKey="INS_ID" Type="TBLINSTRUCTOR" IsForeignKey="true" />
      <Association Name="TBLSTUDENT_TBLPROGRAM" Member="TBLSTUDENT" ThisKey="STUD_ID" OtherKey="STUD_ID" Type="TBLSTUDENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLSTUDENT" Member="TBLSTUDENTs">
    <Type Name="TBLSTUDENT">
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STUD_NO" Type="System.String" DbType="VarChar(10)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="STUD_FNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_MNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_LNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_BDAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="STUD_AGE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STUD_GENDER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_MOBILE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STUD_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_ADDRESS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="STUD_YRLVL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STUD_SCHED" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLSTUDENT_TBLENROLLMENT" Member="TBLENROLLMENTs" ThisKey="STUD_ID" OtherKey="STUD_ID" Type="TBLENROLLMENT" />
      <Association Name="TBLSTUDENT_TBLGRADE" Member="TBLGRADEs" ThisKey="STUD_ID" OtherKey="STUD_ID" Type="TBLGRADE" />
      <Association Name="TBLSTUDENT_TBLPROGRAM" Member="TBLPROGRAMs" ThisKey="STUD_ID" OtherKey="STUD_ID" Type="TBLPROGRAM" />
      <Association Name="TBLUSER_TBLSTUDENT" Member="TBLUSER" ThisKey="USERID" OtherKey="USERID" Type="TBLUSER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLSY" Member="TBLSies">
    <Type Name="TBLSY">
      <Column Name="SY_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SY_START" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SY_END" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLUSER" Member="TBLUSERs">
    <Type Name="TBLUSER">
      <Column Name="USERID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERNO" Type="System.String" DbType="VarChar(10)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_MOBILE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="USER_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_ADDRESS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="USER_ROLE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBLUSER_TBLSTUDENT" Member="TBLSTUDENTs" ThisKey="USERID" OtherKey="USERID" Type="TBLSTUDENT" />
    </Type>
  </Table>
  <Function Name="dbo.sp_admin_delete" Method="sp_admin_delete">
    <Parameter Name="ADMIN_ID" Parameter="aDMIN_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_admin_save" Method="sp_admin_save">
    <Parameter Name="ADMIN_FNAME" Parameter="aDMIN_FNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADMIN_MNAME" Parameter="aDMIN_MNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADMIN_LNAME" Parameter="aDMIN_LNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADMIN_ROLE" Parameter="aDMIN_ROLE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADMIN_USERNAME" Parameter="aDMIN_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADMIN_PASSWORD" Parameter="aDMIN_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_admin_search" Method="sp_admin_search">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_admin_searchResult">
      <Column Name="ADMIN_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ADMIN_NO" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="ADMIN_FNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_MNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_LNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_ROLE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADMIN_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_admin_update" Method="sp_admin_update">
    <Parameter Name="ADMIN_ID" Parameter="aDMIN_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ADMIN_FNAME" Parameter="aDMIN_FNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADMIN_MNAME" Parameter="aDMIN_MNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADMIN_LNAME" Parameter="aDMIN_LNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADMIN_ROLE" Parameter="aDMIN_ROLE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADMIN_USERNAME" Parameter="aDMIN_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ADMIN_PASSWORD" Parameter="aDMIN_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_admin_view" Method="sp_admin_view">
    <ElementType Name="sp_admin_viewResult">
      <Column Name="ADMIN_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ADMIN_NO" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="ADMIN_FNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_MNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_LNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_ROLE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADMIN_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADMIN_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_course_delete" Method="sp_course_delete">
    <Parameter Name="COURSE_ID" Parameter="cOURSE_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_course_save" Method="sp_course_save">
    <Parameter Name="COURSE_NAME" Parameter="cOURSE_NAME" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="COURSE_UNITS" Parameter="cOURSE_UNITS" Type="System.Decimal" DbType="Decimal(4,2)" />
    <Parameter Name="COURSE_STATUS" Parameter="cOURSE_STATUS" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_course_search" Method="sp_course_search">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_course_searchResult">
      <Column Name="COURSE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COURSE_CODE" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="COURSE_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="COURSE_UNITS" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="COURSE_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_course_update" Method="sp_course_update">
    <Parameter Name="COURSE_ID" Parameter="cOURSE_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="COURSE_NAME" Parameter="cOURSE_NAME" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="COURSE_UNITS" Parameter="cOURSE_UNITS" Type="System.Decimal" DbType="Decimal(4,2)" />
    <Parameter Name="COURSE_STATUS" Parameter="cOURSE_STATUS" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_course_view" Method="sp_course_view">
    <ElementType Name="sp_course_viewResult">
      <Column Name="COURSE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COURSE_CODE" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="COURSE_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="COURSE_UNITS" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="COURSE_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_enrollment_delete" Method="sp_enrollment_delete">
    <Parameter Name="ENROLL_ID" Parameter="eNROLL_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_enrollment_search" Method="sp_enrollment_search">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_enrollment_searchResult">
      <Column Name="ENROLL_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ENROLL_NO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="ENROLL_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ENROLL_TIME" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="ENROLL_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_enrollment_save" Method="sp_enrollment_save">
    <Parameter Name="ENROLL_DATE" Parameter="eNROLL_DATE" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ENROLL_TIME" Parameter="eNROLL_TIME" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="ENROLL_STATUS" Parameter="eNROLL_STATUS" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_enrollment_update" Method="sp_enrollment_update">
    <Parameter Name="ENROLL_ID" Parameter="eNROLL_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ENROLL_DATE" Parameter="eNROLL_DATE" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ENROLL_TIME" Parameter="eNROLL_TIME" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="ENROLL_STATUS" Parameter="eNROLL_STATUS" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_enrollment_view" Method="sp_enrollment_view">
    <ElementType Name="sp_enrollment_viewResult">
      <Column Name="ENROLL_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ENROLL_NO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="ENROLL_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ENROLL_TIME" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="ENROLL_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_grade_save" Method="sp_grade_save">
    <Parameter Name="GRADE_VAL" Parameter="gRADE_VAL" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_grade_delete" Method="sp_grade_delete">
    <Parameter Name="GRADE_ID" Parameter="gRADE_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_grade_search" Method="sp_grade_search">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_grade_searchResult">
      <Column Name="GRADE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GRADE_VAL" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COURSE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_grade_update" Method="sp_grade_update">
    <Parameter Name="GRADE_ID" Parameter="gRADE_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GRADE_VAL" Parameter="gRADE_VAL" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_grade_view" Method="sp_grade_view">
    <ElementType Name="sp_grade_viewResult">
      <Column Name="GRADE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GRADE_VAL" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COURSE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_instructor_delete" Method="sp_instructor_delete">
    <Parameter Name="INS_ID" Parameter="iNS_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_instructor_save" Method="sp_instructor_save">
    <Parameter Name="INS_FNAME" Parameter="iNS_FNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="INS_MNAME" Parameter="iNS_MNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="INS_LNAME" Parameter="iNS_LNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="INS_GENDER" Parameter="iNS_GENDER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="INS_BDAY" Parameter="iNS_BDAY" Type="System.DateTime" DbType="Date" />
    <Parameter Name="INS_MOBILE" Parameter="iNS_MOBILE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="INS_EMAIL" Parameter="iNS_EMAIL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="INS_STATUS" Parameter="iNS_STATUS" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_instructor_search" Method="sp_instructor_search">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_instructor_searchResult">
      <Column Name="INS_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="INS_NO" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="INS_FNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_MNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_LNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_GENDER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_BDAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="INS_MOBILE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="INS_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_instructor_update" Method="sp_instructor_update">
    <Parameter Name="INS_ID" Parameter="iNS_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="INS_FNAME" Parameter="iNS_FNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="INS_MNAME" Parameter="iNS_MNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="INS_LNAME" Parameter="iNS_LNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="INS_GENDER" Parameter="iNS_GENDER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="INS_BDAY" Parameter="iNS_BDAY" Type="System.DateTime" DbType="Date" />
    <Parameter Name="INS_MOBILE" Parameter="iNS_MOBILE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="INS_EMAIL" Parameter="iNS_EMAIL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="INS_STATUS" Parameter="iNS_STATUS" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_instructor_view" Method="sp_instructor_view">
    <ElementType Name="sp_instructor_viewResult">
      <Column Name="INS_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="INS_NO" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="INS_FNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_MNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_LNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_GENDER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_BDAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="INS_MOBILE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="INS_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INS_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_program_delete" Method="sp_program_delete">
    <Parameter Name="PROG_ID" Parameter="pROG_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_program_save" Method="sp_program_save">
    <Parameter Name="PROG_DESC" Parameter="pROG_DESC" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="PROG_CREDITS" Parameter="pROG_CREDITS" Type="System.Decimal" DbType="Decimal(4,2)" />
    <Parameter Name="PROG_STATUS" Parameter="pROG_STATUS" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_program_search" Method="sp_program_search">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_program_searchResult">
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PROG_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PROG_DESC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PROG_CREDITS" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="PROG_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COURSE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_program_update" Method="sp_program_update">
    <Parameter Name="PROG_ID" Parameter="pROG_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PROG_DESC" Parameter="pROG_DESC" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="PROG_CREDITS" Parameter="pROG_CREDITS" Type="System.Decimal" DbType="Decimal(4,2)" />
    <Parameter Name="PROG_STATUS" Parameter="pROG_STATUS" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_program_view" Method="sp_program_view">
    <ElementType Name="sp_program_viewResult">
      <Column Name="PROG_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PROG_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PROG_DESC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PROG_CREDITS" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="PROG_STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COURSE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_student_delete" Method="sp_student_delete">
    <Parameter Name="STUD_ID" Parameter="sTUD_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_student_search" Method="sp_student_search">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_student_searchResult">
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STUD_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="STUD_FNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_MNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_LNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_BDAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="STUD_AGE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STUD_GENDER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_MOBILE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STUD_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_ADDRESS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="STUD_YRLVL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STUD_SCHED" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_student_save" Method="sp_student_save">
    <Parameter Name="STUD_FNAME" Parameter="sTUD_FNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STUD_MNAME" Parameter="sTUD_MNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STUD_LNAME" Parameter="sTUD_LNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STUD_BDAY" Parameter="sTUD_BDAY" Type="System.DateTime" DbType="Date" />
    <Parameter Name="STUD_AGE" Parameter="sTUD_AGE" Type="System.Int32" DbType="Int" />
    <Parameter Name="STUD_GENDER" Parameter="sTUD_GENDER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STUD_MOBILE" Parameter="sTUD_MOBILE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="STUD_EMAIL" Parameter="sTUD_EMAIL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STUD_ADDRESS" Parameter="sTUD_ADDRESS" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="STUD_YRLVL" Parameter="sTUD_YRLVL" Type="System.Int32" DbType="Int" />
    <Parameter Name="STUD_SCHED" Parameter="sTUD_SCHED" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_student_update" Method="sp_student_update">
    <Parameter Name="STUD_ID" Parameter="sTUD_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="STUD_FNAME" Parameter="sTUD_FNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STUD_MNAME" Parameter="sTUD_MNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STUD_LNAME" Parameter="sTUD_LNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STUD_BDAY" Parameter="sTUD_BDAY" Type="System.DateTime" DbType="Date" />
    <Parameter Name="STUD_AGE" Parameter="sTUD_AGE" Type="System.Int32" DbType="Int" />
    <Parameter Name="STUD_GENDER" Parameter="sTUD_GENDER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STUD_MOBILE" Parameter="sTUD_MOBILE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="STUD_EMAIL" Parameter="sTUD_EMAIL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="STUD_ADDRESS" Parameter="sTUD_ADDRESS" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="STUD_YRLVL" Parameter="sTUD_YRLVL" Type="System.Int32" DbType="Int" />
    <Parameter Name="STUD_SCHED" Parameter="sTUD_SCHED" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_student_view" Method="sp_student_view">
    <ElementType Name="sp_student_viewResult">
      <Column Name="STUD_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STUD_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="STUD_FNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_MNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_LNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_BDAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="STUD_AGE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STUD_GENDER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_MOBILE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STUD_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STUD_ADDRESS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="STUD_YRLVL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STUD_SCHED" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_sy_delete" Method="sp_sy_delete">
    <Parameter Name="SY_ID" Parameter="sY_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_sy_save" Method="sp_sy_save">
    <Parameter Name="SY_START" Parameter="sY_START" Type="System.DateTime" DbType="Date" />
    <Parameter Name="SY_END" Parameter="sY_END" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_sy_search" Method="sp_sy_search">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_sy_searchResult">
      <Column Name="SY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SY_START" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SY_END" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_sy_update" Method="sp_sy_update">
    <Parameter Name="SY_ID" Parameter="sY_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SY_START" Parameter="sY_START" Type="System.DateTime" DbType="Date" />
    <Parameter Name="SY_END" Parameter="sY_END" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_user_delete" Method="sp_user_delete">
    <Parameter Name="USERID" Parameter="uSERID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_sy_view" Method="sp_sy_view">
    <ElementType Name="sp_sy_viewResult">
      <Column Name="SY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SY_START" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SY_END" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_user_save" Method="sp_user_save">
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_MOBILE" Parameter="uSER_MOBILE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="USER_EMAIL" Parameter="uSER_EMAIL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_ADDRESS" Parameter="uSER_ADDRESS" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="USER_ROLE" Parameter="uSER_ROLE" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_user_search" Method="sp_user_search">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_user_searchResult">
      <Column Name="USERID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USERNO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_MOBILE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="USER_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_ADDRESS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="USER_ROLE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_user_update" Method="sp_user_update">
    <Parameter Name="USERID" Parameter="uSERID" Type="System.Int32" DbType="Int" />
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_MOBILE" Parameter="uSER_MOBILE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="USER_EMAIL" Parameter="uSER_EMAIL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_ADDRESS" Parameter="uSER_ADDRESS" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="USER_ROLE" Parameter="uSER_ROLE" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_user_view" Method="sp_user_view">
    <ElementType Name="sp_user_viewResult">
      <Column Name="USERID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USERNO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_MOBILE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="USER_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_ADDRESS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="USER_ROLE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>